export const SET_USER = 'SET_USER'
export const SET_LOGIN_LOADER = 'SET_LOGIN_LOADER'
export const SET_REGISTER_LOADER = 'SET_REGISTER_LOADER'
export const SET_CHECK_ALREADY_LOADER = 'SET_CHECK_ALREADY_LOADER'
