name: CI

on:
  push:
    branches:
    - master
    - dev

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run build
        run: |
         npm install
         npm run-script build
      - name: Run test
        run: npm run-script test:unit